using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows;
using MessageBox=System.Windows.MessageBox;
namespace MarketWatcher;
public partial class EmailSettingsWindow:Window
{
 private readonly Repository _repo;private readonly WatcherService _watcher;private readonly GeneralSettings _general;private readonly EmailSettings _email;private readonly TelegramSettings _telegram;private readonly WhatsAppSettings _whatsApp;private readonly ObservableCollection<WhatsAppRecipient> _wa;private readonly ObservableCollection<TelegramRecipient> _tg;
 public EmailSettingsWindow(Repository repo,WatcherService watcher){InitializeComponent();_repo=repo;_watcher=watcher;_general=repo.GetGeneral();KeepBrowserOpen.IsChecked=_general.KeepBrowserOpen;SettingsAutoStart.IsChecked=AutoStartManager.IsEnabled();_email=repo.GetEmail();EmailImages.IsChecked=_email.IncludeImages;HostBox.Text=_email.Host;PortBox.Text=_email.Port.ToString();UserBox.Text=_email.User;RecipientBox.Text=_email.Recipient;_telegram=repo.GetTelegram();TelegramEnabled.IsChecked=_telegram.Enabled;TelegramImages.IsChecked=_telegram.IncludeImages;_tg=new(_telegram.Recipients);TelegramGrid.ItemsSource=_tg;_whatsApp=repo.GetWhatsApp();WhatsAppEnabled.IsChecked=_whatsApp.Enabled;WhatsAppImages.IsChecked=_whatsApp.IncludeImages;_wa=new(_whatsApp.Recipients);WhatsAppGrid.ItemsSource=_wa;}
 private void Apply(){AutoStartManager.SetEnabled(SettingsAutoStart.IsChecked==true);_general.KeepBrowserOpen=KeepBrowserOpen.IsChecked==true;_repo.SaveGeneral(_general);_email.IncludeImages=EmailImages.IsChecked==true;_email.Host=HostBox.Text.Trim();_email.Port=int.TryParse(PortBox.Text,out var p)?p:587;_email.User=UserBox.Text.Trim();_email.Recipient=RecipientBox.Text.Trim();if(PasswordBox.Password.Length>0)_email.ProtectedPassword=SecretStore.Protect(PasswordBox.Password);_repo.SaveEmail(_email);_telegram.Enabled=TelegramEnabled.IsChecked==true;_telegram.IncludeImages=TelegramImages.IsChecked==true;if(TelegramTokenBox.Password.Length>0)_telegram.ProtectedBotToken=SecretStore.Protect(TelegramTokenBox.Password);_telegram.Recipients=_tg.ToList();_repo.SaveTelegram(_telegram);_whatsApp.Enabled=WhatsAppEnabled.IsChecked==true;_whatsApp.IncludeImages=WhatsAppImages.IsChecked==true;_whatsApp.UseDesktopApp=false;foreach(var x in _wa)x.Number=new string(x.Number.Where(char.IsDigit).ToArray());_whatsApp.Recipients=_wa.ToList();_repo.SaveWhatsApp(_whatsApp);}
 private void AddWhatsApp_Click(object s,RoutedEventArgs e){var x=new WhatsAppRecipient();_wa.Add(x);WhatsAppGrid.SelectedItem=x;} private void RemoveWhatsApp_Click(object s,RoutedEventArgs e){if(WhatsAppGrid.SelectedItem is WhatsAppRecipient x)_wa.Remove(x);} private void AddTelegram_Click(object s,RoutedEventArgs e){var x=new TelegramRecipient();_tg.Add(x);TelegramGrid.SelectedItem=x;} private void RemoveTelegram_Click(object s,RoutedEventArgs e){if(TelegramGrid.SelectedItem is TelegramRecipient x)_tg.Remove(x);}
 private async void Save_Click(object s,RoutedEventArgs e){Apply();await _watcher.ApplyBrowserPolicyAsync();DialogResult=true;} private void Cancel_Click(object s,RoutedEventArgs e)=>DialogResult=false;
 private async void TelegramTest_Click(object s,RoutedEventArgs e){try{Apply();foreach(var x in _telegram.Recipients)x.Selected=x.Enabled;await TelegramSender.TestAsync(_telegram);MessageBox.Show("Telegram-Test gesendet.");}catch(Exception ex){MessageBox.Show(ex.Message,"Telegram-Fehler");}}
 private async void WhatsAppTest_Click(object s,RoutedEventArgs e){try{Apply();foreach(var x in _whatsApp.Recipients)x.Selected=x.Enabled;await _watcher.TestWhatsAppAsync(_whatsApp);MessageBox.Show("WhatsApp-Testnachricht gesendet.");}catch(Exception ex){MessageBox.Show(ex.Message,"WhatsApp-Anmeldung erforderlich");}}
 private void WhatsAppLogin_Click(object s,RoutedEventArgs e){try{Apply();var edge=BrowserFinder.FindEdge()??throw new InvalidOperationException("Microsoft Edge wurde nicht gefunden.");Process.Start(new ProcessStartInfo(edge,$"--user-data-dir=\"{AppPaths.EdgeProfile}\" https://web.whatsapp.com"){UseShellExecute=true});}catch(Exception ex){MessageBox.Show(ex.Message);}}
}
